### ISSUE TITLE
[19.2] Your In Grave Danger support for custom death system when a Remnant

### ISSUE THREAD

**Issue by Shibva** [ProbablyManuel/requiem#213]
### Is your feature request related to a problem? Please describe.
I am not fully sure because the behavior is iffy; meaning it's most likely its "buggy" because of the lack of integration.

 When you die as a player, even as a remnant that a player, a grave is generated that serves as a means of keeping your equipment in a single grave that when r-clicked (or configured based on the mod's internal config) will restore your inventory and re-equip your gear and items back into the configuration it was in post-death.
 
While this works with the player being a "demon" as the mod describes, it does not when you are using a host (other players' shells I'm not sure of) and will cause the items to spew all over the place like normal. (the exception to this is if you are /kill-ed)

### Describe the solution you'd like
What would be nice is support for this mod but a few special cases added to potentially avoid issues; they can be the following:

- Graves will generate regardless of the entity the player possesses
- The Soulbound enchanted items will not be cleared from the inventory and kept in the "unpossessed" inventory; in the case of a Soulbound amor piece/set entities the processes that have limited inventory (ie, iron golems, animals, etc.) will be ignored (if no measure that deals with that is already in place to keep balance)

### Additional context
The mod is open-sourced and can be found [Here](https://github.com/B1n-ry/Youre-in-grave-danger)

Tested a few things and found some behavior that should be noted if integration is considered:
- If an entity with limited inventory opens a grave, the items will still be added to the inventory regardless; however, the player won't be able to interact with it until they are an inventory-capable host
- Soulbound Enchanted items DO NOT persist in the inventory if you die and don't drop if you are a player and are a remnant. Because the mod prevents players from dropping items and stores them in a grave AND players that die as a remnant are supposed to have a clear inventory; the item, in this case, is ERASED. If integration is done it is safe to assume this issue will expand to all deaths as a remnant (exception is /kill caused) so it should be addressed as well.
- As of this point in time; soulbound items are dropped when a player possessing an entity dies; again this will cause the issue above this bullet to occur if it's integrated and is not considered; (ie, creates a soulbond voiding bug)

**Comment by ProbablyManuel** [comment]
I think you landed at the wrong page. This is the GitHub of the Skyrim mod [Requiem](https://www.nexusmods.com/skyrimspecialedition/mods/60888).
