### ISSUE TITLE
Polymorph spell allows players to "revive" and re-loot dead bodies

### ISSUE THREAD

**Issue by Mieekaserra** [ProbablyManuel/requiem#280]
### Describe the bug
When using the spell polymorph on a dead body, then use it again on the chicken, the body respawns with a additional loot set.

### To Reproduce
When casting Polymorph on a dead body, it will turn into a living chicken. 
When casting polymorph again on the chicken, it will revert to the dead body from before - but with all loot replenished

### Expected behavior
Spell shouldn't work on corpses IMO.

**Comment by ProbablyManuel** [comment]
Fixed in #281
