### ISSUE TITLE
Food Overhaul

### ISSUE THREAD

**Issue by ProbablyManuel** [ProbablyManuel/requiem#292]
- Artificially short duration on food adds nonconstructive tedium.
- Food provides too many stackable effects.
- The effect of food is often arbitrary and not based on the type of nutrition. Some examples:
    - Food added by Hearthfire has special effects solely because it's from Hearthfire.
    - Apple Cabbage Stew restores 1 stamina per second because it has stew in its name. No other vegetable has such an effect.
    - Beef stew uniquely and inexplicably increases health by 50 and carry weight by 25.
- Food is generally too expensive and the good items are very selectively available.

### Expected Outcome

- Most food provides one or more long lasting effect that is determined by the nutrition of the food.
- The four types of nutrition are
    - Vegan: Resist Disease
    - Meat: Fortify Carry Weight
    - Flour: Restore Stamina
    - Dairy: Restore Magicka
- Different effects stack with each other but not with themselves.
- The magnitude is fixed for each nutrition so that there are no useless items. Special and rare food like Mammoth Steak may be exempt from this.)
- The duration scales with food size and rarity (e.g. a potato soup lasts longer then a potato).
- Beast races receive a special food bonus:
    - Argonian: Eating fish ingredients has 5 times higher magnitude.
    - Bosmer: Raw Meat has double magnitude.
    - Khajiit: Elswyr Fondue has double magnitude.
    - Orc: Can eat Wrothgar Tartare (formerly known as Bestial Stew) which increases health by 25.
- Innkeepers offer a greater variety of food so that each effect is available everywhere.
- Innkeepers sell meat only as stews.
- Buying from innkeepers always occurs at the real price.
- Eating raw meat applies the disease Food Poisoning which drains magicka and stamina by 50.
- The Atronach Stone doesn't penalize food.
- The magicka and stamina penalty from food is doubled when not under the effect of any food buff.

**Comment by jtux270** [comment]
Apologies if here is the wrong place for user suggestions, but is it possible to add the possibility to buy beef and eidar cheese wheels from all kind of food sellers (innkeepers, markets etc) in plenty? We all know economics is broken/non-existent in vanilla, but for the Requiem sake would you please please make those priceless items more or less abundant? Pretty sure every Requiem player would be happy not to kill cows/add cheese wheels through console anymore but just go and buy them in game. TY!

**Comment by ProbablyManuel** [comment]
There are no plans to make innkeepers sell raw beef because they want to sell the processed beef stew instead. However, with the combined changes in this issue there should no longer be a compelling reason for the player to acquire raw beef. Beef stew will be an equal option to the other meat stews, and it will be commonly available at innkeepers for a reasonable price.

Eidar cheese wheels will have a chance to be purchasable from innkeepers.
