### ISSUE TITLE
Bad Instructions

### ISSUE THREAD

**Issue by lfricken** [ProbablyManuel/requiem#341]
[With Vortex](https://github.com/ProbablyManuel/requiem/wiki/Installing-Requiem-with-Vortex) instructions say `<path to the data folder in your skyrim installation>\Reqtificator.bat` when it should be `<path to the data folder in your skyrim installation>\Data\Reqtificator.bat`

**Comment by ProbablyManuel** [comment]
> <path to the **data** folder in your skyrim installation>\Reqtificator.bat

The instructions already state that the path should include the Data folder.
